export const API_ENDPOINTS = {
  SHOP_BANNERS:"shop-banners",
  MENU_BUILDERS:"menu-builder",
  CATEGORIES: "categories",
  PRODUCTS: "products",
  POPULAR_PRODUCTS: "popular-products",
  SOLITAIRE_PRODUCTS: "solitaireindex",
  NONSOLITAIRE_PRODUCTS: "nonsolitaireindex",
  SETTINGS: "settings",
  CUSTOMER: "me",
  COUPONS: "coupons",
  PARENT_CATEGORIES: "categories",
  FEATURED_CATEGORIES: "featured-categories",
  TYPE: "types",
  UPLOAD: "attachments",
  ORDER: "orders",
  ORDER_STATUS: "order-status",
  LOGIN: "token",
  SOCIAL_LOGIN: "social-login-token",
  REGISTER: "register",
  FORGET_PASSWORD: "forget-password",
  LOGOUT: "logout",
  CHANGE_PASSWORD: "change-password",
  RESET_PASSWORD: "reset-password",
  VERIFY_FORGET_PASSWORD: "verify-forget-password-token",
  VERIFY_CHECKOUT: "orders/checkout/verify",
  CONTACT: "contact-us",
  UPLOAD_DESIGN: "upload-design",
  UPLOAD_DESIGN_IMAGE: "upload-design-image",
  ADDRESS: "address",
  ATTRIBUTES: "attributes",
  SHOPS: "shops",
  ORDERS: "orders",
  SEND_OTP_CODE: "send-otp-code",
  VERIFY_OTP_CODE: "verify-otp-code",
  OTP_LOGIN: "otp-login",
  UPDATE_CONTACT: "update-contact",
  CUSTOMERS: "users",
  TAGS: "tags",
  SHOP_UNDER_MAINTAINANCE: "shop-under-maintainance",
  TAXES: "orders/checkout/get-all-taxes",
  LUCKY: "lucky"
};
